name: Build devcontainer ubuntu image

on:
  push:
    branches: [ "main" ]
    paths:
      - ubuntu/Dockerfile
  workflow_dispatch:
env:
  IMAGE_NAME: ubuntu
  
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get the current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ubuntu
        push: true
        tags: |
          roeeez/ubuntu:latest
          roeeez/ubuntu:${{ steps.date.outputs.date }}-${{ github.run_number }}
        platforms: linux/amd64,linux/arm64
